/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData loading = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData options = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData placeholder = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_cart = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_down = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_left = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_up = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_r = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_complete = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_pressed = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData params = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  }
